### ISSUE TITLE
KiCad

### ISSUE THREAD

**Issue by bigtree908** [ploopyco/mouse#3]
Could the Schematics be posted in a KiCad compatible format?

**Comment by keyboard-magpie** [comment]
It's designed in altium so transferring it across is not trivial. You can create an altium account and use their online viewer for free to view schema/pcb files and even create gerbers.

**Comment by Riesi** [comment]
Not sure if anyone has notifications enabled for this issue still.

But I ported the Altium files to KiCAD. Be aware that I haven't verified the correctness of the design as described in the README disclaimer! I only made the DRC happy and made sure the 3D view is correct for now. 
https://github.com/Riesi/ploopy_mouse_kicad

**Comment by Riesi** [comment]
Ok I already found a difference at the optical sensor :sweat_smile: 
I hope I can get the Gerber diff working soon!
