### ISSUE TITLE
Choice of more standard-sized switches

### ISSUE THREAD

**Issue by silverhook** [ploopyco/mouse#4]
I really like the concept of both the Ploopy mouse and trackball.

But especially since it’s OSHW, I’d probably like to modify it to my liking.

One of the things that I noticed with my mice is that I prefer other switches for the buttons (and wheel encoders). And I was surprised that Ploopy uses a different size switches than all the mice I’ve had so far.

Would it be possible to easily replace the switches (and encoder) with more standard format ones?

(e.g. here’s a pretty good guide for [different switches](https://mouseclub.co/pages/mouse-switch-guide) and another one for [different encoders](https://mouseclub.co/pages/encoder-guide))

**Comment by ploopyco** [comment]
The D2LS switch is quite common, and is arguably easier to replace than its thru-hole cousins. That said, we'd be happy to look at contributions in the form of a PR. :)
