### ISSUE TITLE
Hardware Update?

### ISSUE THREAD

**Issue by pyrotelekinetic** [ploopyco/mouse#6]
It seems like the mechanical hardware files here don't match what I got in the pre-assembled ploopy mouse I purchased from [ploopy.co](https://ploopy.co/mouse) around August of 2021.

Could the files here be updated? Ideally each revision would be available, at least as a git tag.

Thanks, can't wait to print a replacement part so I can get back to using my favorite mouse!

**Comment by ploopyco** [comment]
Please send us an email at contact@ploopy.co and we'll get you sorted out. The original mouse design (which I think you have one of) wasn't open source, and was later replaced with one that's much easier to assemble/print.
